services:
  - type: web
    name: esp32-base-station
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars: []
    autoDeploy: true
    runtimeEnv: python
    region: oregon
    healthCheckPath: /
    ports:
      - 10000
